FROM python:3.9
ENV PYTHONUNBUFFERED 1
WORKDIR /app
COPY requirements.txt /app/requirements.txt
RUN pip3 install -r requirements.txt
CMD python3 manage.py runserver 0.0.0.0:8000




# write  can u turn this to C

